@isTest
public class TestClass {
    public static testmethod void main(){
        
        FirstClass obj= new FirstClass();
        //SecondClass obj1= new secondClass();
        obj.input(10,20);
        obj.process();
        obj.output();
        obj.input(100,200);
        obj.process();
        obj.output();
        obj.input(1000,2000);
        obj.process();
        obj.output();
  
        
    }
}